export default {
  login: "ssifu",
  id: 63223565,
  node_id: "MDQ6VXNlcjYzMjIzNTY1",
  avatar_url: "https://avatars.githubusercontent.com/u/63223565?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/ssifu",
  html_url: "https://github.com/ssifu",
  followers_url: "https://api.github.com/users/ssifu/followers",
  following_url: "https://api.github.com/users/ssifu/following{/other_user}",
  gists_url: "https://api.github.com/users/ssifu/gists{/gist_id}",
  starred_url: "https://api.github.com/users/ssifu/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/ssifu/subscriptions",
  organizations_url: "https://api.github.com/users/ssifu/orgs",
  repos_url: "https://api.github.com/users/ssifu/repos",
  events_url: "https://api.github.com/users/ssifu/events{/privacy}",
  received_events_url: "https://api.github.com/users/ssifu/received_events",
  type: "User",
  site_admin: false,
  name: "Samiul Baree Sifat",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 21,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2020-04-06T05:36:35Z",
  updated_at: "2023-10-10T12:59:33Z",
};
